language: csharp
dist: trusty
mono: none
dotnet: 3.1
install:
- dotnet restore
script:
- dotnet build
- dotnet test --configuration "Release" --collect "Code Coverage" --settings ".\CodeCoverage.runsettings"